Location.create(photo_img: "app/assets/images/locations/kleinfeldhotelblocks.png ", url: "kleinfeldhotelblocks.com", address: "110 W 20th St New York, NY 10011", name: "Kleinfeld Hotel Blocks")
Location.create(photo_img: " ", url: " http://hamptoninn3.hilton.com/en/hotels/new-york/hampton-inn-brooklyn-downtown-NYCBOHX", address: "125 Flatbush Ave Extension, Downtown Brooklyn, NY 11201", name: "Hampton Inn Brooklyn Downtown")
Location.create(photo_img: " ", url: "henrynormanhotel.com", address: "251 N Henry St, Greenpoint, NY 11222", name: "Henry Norman Hotel")
Location.create(photo_img: " ", url: "casablancahotel.com", address: "147 W 43rd St, New York, NY 10036", name: "Casablanca Hotel")
Location.create(photo_img: " ", url: "thewilliamvale.com", address: "111 N 12th St, Williamsburg, Brooklyn, NY 11249", name: "The William Vale Hotel")
Location.create(photo_img: " ", url: "1hotels.com/brooklyn-bridge", address: "60 Furman St Brooklyn, NY, 11201", name: "1 Hotel Brooklyn Bridge")
Location.create(photo_img: " ", url: "hotellejolie.com", address: "235 Meeker Ave, Brooklyn, NY 11211", name: "Hotel Le Jolie")
Location.create(photo_img: " ", url: "ludlowhotel.com", address: "180 Ludlow St, New York NY 10002", name: "The Ludlow New York City")
